panier:
    path:     /
    defaults: { _controller: "EcommerceBundle:Panier:index" }

livraison:
    path:     /livraison
    defaults: { _controller: "EcommerceBundle:Panier:livraison" }

validation:
    path:     /validation
    defaults: { _controller: "EcommerceBundle:Panier:validation" }

ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: "EcommerceBundle:Panier:ajouter" }

supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: "EcommerceBundle:Panier:supprimer" }

livraisonAdresseSuppression:
    path:     /livraison/adresse/suppression/{id}
    defaults: { _controller: "EcommerceBundle:Panier:supprimerAdresse" }